#!/bin/bash

if [[ ! -d ~/Development/go ]]
then
  mkdir -p ~/Development/go
fi

if [[ ! -d ~/.dev-env ]]
then
  mkdir -p ~/.dev-env
fi

cp -r ./env/ ~/.dev-env/

docker run --name dev-env \
           --rm \
           --tty \
           --interactive \
           --publish 8080:8080 \
           --publish 8443:8443 \
           --volume /home/developer/.vim \
           --volume ~/Development/go:/go:rw \
           --volume ~/.dev-env:/home/developer \
           --volume ~/.ssh:/home/developer/.ssh:ro \
           --volume /var/run/docker.sock:/var/run/docker.sock \
           cagiti/dev-env:latest /bin/bash
