#!/bin/bash

[ ! -z "$CLOUD_SHELL" ] && ENV=cloud || ENV=mac
source ./env/env.sh $ENV

if [ $(export | grep -c DISPLAY) -gt 0 ]
then
  PORT=$(ps -ef | grep "Xquartz :\d" | grep -v xinit | awk '{ print $9; }')
  X11_PATH=${DISPLAY/:0}
  display="--env DISPLAY=host.docker.internal${PORT}"
else
  display=""
fi

docker pull rycus86/goland:latest
docker run --rm \
  --detach \
  ${display} \
  --security-opt=seccomp:unconfined \
  --volume ${X11_PATH}:/tmp/.X11-unix \
  --volume ~/.GoLand:/home/developer/.GoLand \
  --volume ~/.GoLand.java:/home/developer/.java \
  --volume ~/Development/go:/home/developer/go \
  --name goland-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
  rycus86/goland:latest
