#!/bin/bash

[ ! -z "$CLOUD_SHELL" ] && ENV=cloud || ENV=mac
source ./env/env.sh $ENV

if [ -z $DISPLAY ]
then
  echo "${X11_ERROR}"
  exit 1
fi

function setup_env_vars() {
  PORT=$(ps -ef | grep "Xquartz :\d" | grep -v xinit | awk '{ print $9; }')
  display="--env DISPLAY=$(hostname)${PORT}"
}

function setup_xquartz() {
  if [ -x $XHOST ]
  then
    [ -z $(pgrep Xquartz) ] && $XHOST
    if [ `$XHOST | grep -ic $(hostname)` -eq 0 ]
    then
      xhost + $(hostname)
    fi
  else
    echo "${XQUARTZ_ERROR}"
  fi
}

function pull_latest() {
  docker pull ${GOLAND}
}

function run() {
  docker run --rm \
             --detach \
             ${display} \
             --security-opt=seccomp:unconfined \
             --volume ${DISPLAY/:0}:/tmp/.X11-unix \
             --volume ~/.GoLand:/home/developer/.GoLand \
             --volume ~/.GoLand.java:/home/developer/.java \
             --volume $WORKSPACE/go:/home/developer/go \
             --name goland-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
             ${GOLAND}
}

setup_xquartz
setup_env_vars
pull_latest
run
